on: workflow_call

# * installs sitemap generator
# * runs generator with priority map and lastmod
# * saves file output to ui/public/sitemap.xml
# * commits output to branch
# * opens pull request

defaults:
  run:
    working-directory: ui/public

jobs:
  sitemap:
    runs-on: ubuntu-latest
    name: Generate xml sitemap
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install sitemap-generator-cli
        run: npm install -g sitemap-generator-cli
      - name: Generate sitemap
        id: sitemap
        run: |
          npx sitemap-generator-cli -lqgv --verbose -p "1.0,0.8,0.6,0.4,0.2" https://data.standards.nhs.uk
          pwd
          cat sitemap.xml
          # add a newline to the sitemap at the end of the file
          echo >> sitemap.xml
          echo "::set-output name=date::`date`"
          echo "::set-output name=workflowurl::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID?check_suite_focus=true"

      - name: Create Pull Request
        env:
          GITHUB_WORKFLOW_URL: ${{ steps.sitemap.outputs.workflowurl }}
          DATE: ${{ steps.sitemap.outputs.date }}
        uses: peter-evans/create-pull-request@v4
        with:
          branch: sitemap-updates
          commit-message: Automated sitemap commit, generated by ${{ env.GITHUB_WORKFLOW_URL }}
          title: Merge in latest sitemap from sitemap workflow. ðŸ—º
          body: |
            Update sitemap.xml from workflow ${{env.GITHUB_WORKFLOW_URL}}

            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          committer: Sitemap Bot ðŸ—ºðŸ¤–ðŸ—º <hello@marvell-consulting.com>
          labels: |
            sitemap
            automated pr
          assignees: roc
          reviewers: |
            roc
            easternbloc
            joefitter
            iebarat
